version: "3"

services:
  sermas-ros-proxy:
    image: sermas/ros-proxy
    restart: unless-stopped
    build:
      context: .
    command: ros2 launch ros_proxy launch.py
    environment:
      - SERMAS_TOOLKIT_URL=https://dev.sermas.spindoxlabs.it
      - APP_ID={appId}
      - CLIENT_ID={clientId}
      - CLIENT_SECRET={clientSecret}
      - LOGLEVEL=INFO
    network_mode: host
    ipc: host
  bridge:
    image: ros:galactic-ros1-bridge
    restart: unless-stopped
    environment:
      - "ROS_MASTER_URI=http://{ROBOT_URL}:11311"
      - "ROS_IP={HOST_IP}"
    command: ros2 run ros1_bridge dynamic_bridge
    network_mode: host
    ipc: host

