version: "3"

services:
  sermas-ros-proxy:
    image: sermas/ros-proxy
    restart: unless-stopped
    build:
      context: .
    command: ros2 launch ros_proxy launch.py
    environment:
      - SERMAS_TOOLKIT_URL=https://dev.sermas.spindoxlabs.it
      - APP_ID=spxl
      - CLIENT_ID=avatar
      - CLIENT_SECRET=6736d73f7f25ab272b6454cefd471d78d74f338b6e634118
      - LOGLEVEL=INFO
    network_mode: host
    pid: host
    ipc: host

  interaction-manager:
    image: sermas/intention-detection
    network_mode: host
    pid: host
    ipc: host
    privileged: true
    command: ros2 launch interaction_manager interaction_manager.launch.xml interaction_trigger_prediction_threshold:=0.5 interaction_end_distance_threshold:=2.0 debug_node:=true

  bag-player:
    image: sermas/intention-detection
    network_mode: host
    pid: host
    ipc: host
    privileged: true
    command: ros2 bag play -l /data/rosbag2_2024_07_19-15_32_02/rosbag2_2024_07_19-15_32_02_0.db3
    volumes:
      - ./logs:/root/.ros/log:rw
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - ./profile.xml:/profile.xml
      - /home/marco/Documents/sermas/bag:/data
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - "FASTRTPS_DEFAULT_PROFILES_FILE=/profile.xml"