# add git branch to bash prompt
parse_git_branch() {
             git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

export PS1="\[\e[01;32m\]\\u@\h\[\e[00m\]:\[\e[01;34m\]\w \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ "

# enable git autocomplition
source /usr/share/bash-completion/completions/git

# change bash history file
export HISTFILE=/home/dev/hist/.bash_history